Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Delete
    Properties:
      Engine: mysql
      AllocatedStorage: 20
      BackupRetentionPeriod: 1
      StorageType: gp2
      DBName: development
      DBInstanceClass: db.t2.micro
      MasterUsername: master_user
      MasterUserPassword: Bowman#88
