# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Delete
    Properties:
      Engine: postgres
      AllocatedStorage: 20
      BackupRetentionPeriod: 1
      StorageType: gp2
      DBName: development
      DBInstanceClass: db.t2.micro
      MasterUsername: master_user
      MasterUserPassword: Bowman#88
Outputs:
  Endpoint:
    Description: Database connection details
    Value: !Join [":", [!GetAtt DB.Endpoint.Address, !GetAtt DB.Endpoint.Port]]